export const heroList = [
    {
    id: 0,
    name: "Abaddon",
    url: "https://dota2.gamepedia.com/Abaddon",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/2/26/Abaddon_icon.png?version=1b9f117778a2c6daaf4a28cc7920a547",
    primaryAttribute: "Strength",
    health: 660,
    healthReg: 2.3,
    mana: 327,
    manaReg: 1.05,
    armor: 1.68,
    attackSpeed: 0.72,
    damage: "55‒65",
    moveSpeed: 325,
    attackRange: "melee",
    roles: [
    "Support",
    "Carry",
    "Durable"
    ]
    },
    {
    id: 1,
    name: "Alchemist",
    url: "https://dota2.gamepedia.com/Alchemist",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/f/fe/Alchemist_icon.png?version=a7c13bea85d68e59c5400c1bd99d1cfb",
    primaryAttribute: "Strength",
    health: 700,
    healthReg: 2.5,
    mana: 375,
    manaReg: 1.25,
    armor: 2.52,
    attackSpeed: 0.72,
    damage: "49‒58",
    moveSpeed: 305,
    attackRange: "melee",
    roles: [
    "Carry",
    "Support",
    "Durable",
    "Disabler",
    "Initiator",
    "Nuker"
    ]
    },
    {
    id: 2,
    name: "Axe",
    url: "https://dota2.gamepedia.com/Axe",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/2/23/Axe_icon.png?version=e684255614f57796dc1a65df620c5191",
    primaryAttribute: "Strength",
    health: 700,
    healthReg: 5.25,
    mana: 291,
    manaReg: 0.9,
    armor: 1.2,
    attackSpeed: 0.71,
    damage: "49‒53",
    moveSpeed: 295,
    attackRange: "melee",
    roles: [
    "Initiator",
    "Durable",
    "Disabler",
    "Jungler"
    ]
    },
    {
    id: 3,
    name: "Beastmaster",
    url: "https://dota2.gamepedia.com/Beastmaster",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d9/Beastmaster_icon.png?version=5aa86ba5bbaca098fe5f9e86bbe132f4",
    primaryAttribute: "Strength",
    health: 660,
    healthReg: 2.3,
    mana: 267,
    manaReg: 0.8,
    armor: 1.88,
    attackSpeed: 0.69,
    damage: "64‒68",
    moveSpeed: 305,
    attackRange: "melee",
    roles: [
    "Initiator",
    "Disabler",
    "Durable",
    "Nuker"
    ]
    },
    {
    id: 4,
    name: "Brewmaster",
    url: "https://dota2.gamepedia.com/Brewmaster",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/1/1e/Brewmaster_icon.png?version=c0906f71595d5e6917c14b54cd1821d3",
    primaryAttribute: "Strength",
    health: 660,
    healthReg: 2.8,
    mana: 243,
    manaReg: 0.7,
    armor: 1.52,
    attackSpeed: 0.72,
    damage: "52‒59",
    moveSpeed: 305,
    attackRange: "melee",
    roles: [
    "Carry",
    "Initiator",
    "Durable",
    "Disabler",
    "Nuker"
    ]
    },
    {
    id: 5,
    name: "Bristleback",
    url: "https://dota2.gamepedia.com/Bristleback",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/4/4d/Bristleback_icon.png?version=77ce3fefc668df38a8c90268dc5bcd8b",
    primaryAttribute: "Strength",
    health: 640,
    healthReg: 2.2,
    mana: 243,
    manaReg: 0.7,
    armor: 2.72,
    attackSpeed: 0.65,
    damage: "44‒54",
    moveSpeed: 290,
    attackRange: "melee",
    roles: [
    "Carry",
    "Durable",
    "Initiator",
    "Nuker"
    ]
    },
    {
    id: 6,
    name: "Centaur Warrunner",
    url: "https://dota2.gamepedia.com/Centaur_Warrunner",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/e/ed/Centaur_Warrunner_icon.png?version=0ebbf51ef4b45ddd509450ac454a0dfa",
    primaryAttribute: "Strength",
    health: 740,
    healthReg: 2.7,
    mana: 255,
    manaReg: 0.75,
    armor: 1.4,
    attackSpeed: 0.68,
    damage: "63‒65",
    moveSpeed: 300,
    attackRange: "melee",
    roles: [
    "Durable",
    "Initiator",
    "Disabler",
    "Nuker",
    "Escape"
    ]
    },
    {
    id: 7,
    name: "Chaos Knight",
    url: "https://dota2.gamepedia.com/Chaos_Knight",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/f/fe/Chaos_Knight_icon.png?version=b321a84d401423e904159e6a380abe12",
    primaryAttribute: "Strength",
    health: 640,
    healthReg: 2.2,
    mana: 291,
    manaReg: 0.9,
    armor: 3.24,
    attackSpeed: 0.67,
    damage: "51‒81",
    moveSpeed: 320,
    attackRange: "melee",
    roles: [
    "Carry",
    "Disabler",
    "Durable",
    "Pusher",
    "Initiator"
    ]
    },
    {
    id: 8,
    name: "Clockwerk",
    url: "https://dota2.gamepedia.com/Clockwerk",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d8/Clockwerk_icon.png?version=079dcb0e7d50a1aba6c833753da60bcf",
    primaryAttribute: "Strength",
    health: 720,
    healthReg: 2.6,
    mana: 279,
    manaReg: 0.85,
    armor: 1.08,
    attackSpeed: 0.66,
    damage: "50‒52",
    moveSpeed: 310,
    attackRange: "melee",
    roles: [
    "Initiator",
    "Disabler",
    "Durable",
    "Nuker"
    ]
    },
    {
    id: 9,
    name: "Doom",
    url: "https://dota2.gamepedia.com/Doom",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/4/40/Doom_icon.png?version=2240f491fb558e9ea1b0619b53517c82",
    primaryAttribute: "Strength",
    health: 720,
    healthReg: 2.6,
    mana: 255,
    manaReg: 0.75,
    armor: 0.76,
    attackSpeed: 0.56,
    damage: "53‒69",
    moveSpeed: 285,
    attackRange: "melee",
    roles: [
    "Carry",
    "Disabler",
    "Initiator",
    "Durable",
    "Nuker"
    ]
    },
    {
    id: 10,
    name: "Dragon Knight",
    url: "https://dota2.gamepedia.com/Dragon_Knight",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/5/59/Dragon_Knight_icon.png?version=8f081d5debb0efc6f95282c7a1c52c68",
    primaryAttribute: "Strength",
    health: 580,
    healthReg: 1.9,
    mana: 255,
    manaReg: 0.75,
    armor: 3.04,
    attackSpeed: 0.7,
    damage: "50‒56",
    moveSpeed: 295,
    attackRange: "melee",
    roles: [
    "Carry",
    "Pusher",
    "Durable",
    "Disabler",
    "Initiator",
    "Nuker"
    ]
    },
    {
    id: 11,
    name: "Earth Spirit",
    url: "https://dota2.gamepedia.com/Earth_Spirit",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/b/be/Earth_Spirit_icon.png?version=6358ee2b1e31c856ff16cb7fb5e23f46",
    primaryAttribute: "Strength",
    health: 620,
    healthReg: 2.1,
    mana: 291,
    manaReg: 0.9,
    armor: 2.72,
    attackSpeed: 0.69,
    damage: "46‒56",
    moveSpeed: 290,
    attackRange: "melee",
    roles: [
    "Nuker",
    "Escape",
    "Disabler",
    "Initiator",
    "Durable"
    ]
    },
    {
    id: 12,
    name: "Earthshaker",
    url: "https://dota2.gamepedia.com/Earthshaker",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a5/Earthshaker_icon.png?version=7f16a63e5ed6a7ec7a3889dd4aea354d",
    primaryAttribute: "Strength",
    health: 640,
    healthReg: 3.2,
    mana: 267,
    manaReg: 0.8,
    armor: 3.92,
    attackSpeed: 0.66,
    damage: "49‒59",
    moveSpeed: 310,
    attackRange: "melee",
    roles: [
    "Support",
    "Initiator",
    "Disabler",
    "Nuker"
    ]
    },
    {
    id: 13,
    name: "Elder Titan",
    url: "https://dota2.gamepedia.com/Elder_Titan",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/1/1a/Elder_Titan_icon.png?version=e2649f981d5f6dcc1d16bbaefadc2324",
    primaryAttribute: "Strength",
    health: 680,
    healthReg: 2.4,
    mana: 351,
    manaReg: 1.15,
    armor: 2.24,
    attackSpeed: 0.67,
    damage: "47‒57",
    moveSpeed: 310,
    attackRange: "melee",
    roles: [
    "Initiator",
    "Disabler",
    "Nuker",
    "Durable"
    ]
    },
    {
    id: 14,
    name: "Huskar",
    url: "https://dota2.gamepedia.com/Huskar",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d3/Huskar_icon.png?version=310e94592950b90783d934a87591e05d",
    primaryAttribute: "Strength",
    health: 620,
    healthReg: 2.1,
    mana: 291,
    manaReg: 0.9,
    armor: 0.4,
    attackSpeed: 0.72,
    damage: "40‒45",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Carry",
    "Durable",
    "Initiator"
    ]
    },
    {
    id: 15,
    name: "Io",
    url: "https://dota2.gamepedia.com/Io",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8d/Io_icon.png?version=94a7476345faa617842c26f446a26ec4",
    primaryAttribute: "Strength",
    health: 540,
    healthReg: 1.7,
    mana: 351,
    manaReg: 1.15,
    armor: 0.24,
    attackSpeed: 0.67,
    damage: "39‒48",
    moveSpeed: 280,
    attackRange: "range",
    roles: [
    "Support",
    "Escape",
    "Nuker"
    ]
    },
    {
    id: 16,
    name: "Kunkka",
    url: "https://dota2.gamepedia.com/Kunkka",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c0/Kunkka_icon.png?version=f64791660d48f854ce9ce85eb233af3b",
    primaryAttribute: "Strength",
    health: 680,
    healthReg: 2.4,
    mana: 291,
    manaReg: 0.9,
    armor: 3.24,
    attackSpeed: 0.67,
    damage: "50‒60",
    moveSpeed: 300,
    attackRange: "melee",
    roles: [
    "Carry",
    "Support",
    "Disabler",
    "Initiator",
    "Durable",
    "Nuker"
    ]
    },
    {
    id: 17,
    name: "Legion Commander",
    url: "https://dota2.gamepedia.com/Legion_Commander",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a2/Legion_Commander_icon.png?version=82c151a5cd968eba51cfb442831f94af",
    primaryAttribute: "Strength",
    health: 720,
    healthReg: 2.6,
    mana: 315,
    manaReg: 1,
    armor: 1.88,
    attackSpeed: 0.69,
    damage: "61‒65",
    moveSpeed: 330,
    attackRange: "melee",
    roles: [
    "Carry",
    "Disabler",
    "Initiator",
    "Durable",
    "Nuker"
    ]
    },
    {
    id: 18,
    name: "Lifestealer",
    url: "https://dota2.gamepedia.com/Lifestealer",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/2/2b/Lifestealer_icon.png?version=2fd62b82d2c618c9b6f1b69ba6b8d509",
    primaryAttribute: "Strength",
    health: 700,
    healthReg: 2.5,
    mana: 255,
    manaReg: 0.75,
    armor: 2.88,
    attackSpeed: 0.64,
    damage: "52‒62",
    moveSpeed: 325,
    attackRange: "melee",
    roles: [
    "Carry",
    "Durable",
    "Jungler",
    "Escape",
    "Disabler"
    ]
    },
    {
    id: 19,
    name: "Lycan",
    url: "https://dota2.gamepedia.com/Lycan",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d6/Lycan_icon.png?version=8174f47b42eaebb44f401927252765cb",
    primaryAttribute: "Strength",
    health: 700,
    healthReg: 2.5,
    mana: 279,
    manaReg: 0.85,
    armor: 1.56,
    attackSpeed: 0.68,
    damage: "55‒60",
    moveSpeed: 315,
    attackRange: "melee",
    roles: [
    "Carry",
    "Pusher",
    "Jungler",
    "Durable",
    "Escape"
    ]
    },
    {
    id: 20,
    name: "Magnus",
    url: "https://dota2.gamepedia.com/Magnus",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/b/ba/Magnus_icon.png?version=a59de522b23eddce524eec08e6598a9b",
    primaryAttribute: "Strength",
    health: 660,
    healthReg: 2.8,
    mana: 303,
    manaReg: 0.95,
    armor: 3.4,
    attackSpeed: 0.64,
    damage: "55‒67",
    moveSpeed: 305,
    attackRange: "melee",
    roles: [
    "Initiator",
    "Disabler",
    "Nuker",
    "Escape"
    ]
    },
    {
    id: 21,
    name: "Mars",
    url: "https://dota2.gamepedia.com/Mars",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/9/9d/Mars_icon.png?version=52c12b93be5c87fe1345fdb20b24fb5d",
    primaryAttribute: "Strength",
    health: 660,
    healthReg: 2.3,
    mana: 279,
    manaReg: 0.85,
    armor: 3.2,
    attackSpeed: 0.67,
    damage: "58‒66",
    moveSpeed: 310,
    attackRange: "melee",
    roles: [
    "Carry",
    "Initiator",
    "Disabler",
    "Durable"
    ]
    },
    {
    id: 22,
    name: "Night Stalker",
    url: "https://dota2.gamepedia.com/Night_Stalker",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/1/15/Night_Stalker_icon.png?version=89360dbfb748a26ff50bcb475feb9d5b",
    primaryAttribute: "Strength",
    health: 660,
    healthReg: 4.05,
    mana: 231,
    manaReg: 0.65,
    armor: 4.88,
    attackSpeed: 0.69,
    damage: "61‒65",
    moveSpeed: 290,
    attackRange: "melee",
    roles: [
    "Carry",
    "Initiator",
    "Durable",
    "Disabler",
    "Nuker"
    ]
    },
    {
    id: 23,
    name: "Omniknight",
    url: "https://dota2.gamepedia.com/Omniknight",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/e/e2/Omniknight_icon.png?version=69fb42b317ef5d5495fd566090baec8f",
    primaryAttribute: "Strength",
    health: 640,
    healthReg: 2.2,
    mana: 255,
    manaReg: 0.75,
    armor: 4.4,
    attackSpeed: 0.68,
    damage: "53‒63",
    moveSpeed: 300,
    attackRange: "melee",
    roles: [
    "Support",
    "Durable",
    "Nuker"
    ]
    },
    {
    id: 24,
    name: "Phoenix",
    url: "https://dota2.gamepedia.com/Phoenix",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/1/14/Phoenix_icon.png?version=db8f4ec5840022a97ce532d138af8f13",
    primaryAttribute: "Strength",
    health: 580,
    healthReg: 1.9,
    mana: 291,
    manaReg: 0.9,
    armor: -0.08,
    attackSpeed: 0.66,
    damage: "45‒55",
    moveSpeed: 280,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker",
    "Initiator",
    "Escape",
    "Disabler"
    ]
    },
    {
    id: 25,
    name: "Pudge",
    url: "https://dota2.gamepedia.com/Pudge",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c0/Pudge_icon.png?version=fee1223645079c94aacce19357e9a416",
    primaryAttribute: "Strength",
    health: 700,
    healthReg: 2.5,
    mana: 243,
    manaReg: 0.7,
    armor: 0.24,
    attackSpeed: 0.67,
    damage: "65‒71",
    moveSpeed: 280,
    attackRange: "melee",
    roles: [
    "Disabler",
    "Initiator",
    "Durable",
    "Nuker"
    ]
    },
    {
    id: 26,
    name: "Sand King",
    url: "https://dota2.gamepedia.com/Sand_King",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/7/79/Sand_King_icon.png?version=eda0d31413598822d2190b790f56a0a5",
    primaryAttribute: "Strength",
    health: 640,
    healthReg: 2.2,
    mana: 303,
    manaReg: 0.95,
    armor: 2.04,
    attackSpeed: 0.7,
    damage: "45‒55",
    moveSpeed: 290,
    attackRange: "melee",
    roles: [
    "Initiator",
    "Disabler",
    "Support",
    "Nuker",
    "Escape",
    "Jungler"
    ]
    },
    {
    id: 27,
    name: "Slardar",
    url: "https://dota2.gamepedia.com/Slardar",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7e/Slardar_icon.png?version=a47d98fe72c0976d67582f3bc223c069",
    primaryAttribute: "Strength",
    health: 620,
    healthReg: 2.1,
    mana: 255,
    manaReg: 0.75,
    armor: 5.72,
    attackSpeed: 0.69,
    damage: "51‒59",
    moveSpeed: 290,
    attackRange: "melee",
    roles: [
    "Carry",
    "Durable",
    "Initiator",
    "Disabler",
    "Escape"
    ]
    },
    {
    id: 28,
    name: "Spirit Breaker",
    url: "https://dota2.gamepedia.com/Spirit_Breaker",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/d/df/Spirit_Breaker_icon.png?version=166d65dd74ef0676fd3a12d1a1504e5d",
    primaryAttribute: "Strength",
    health: 780,
    healthReg: 3.65,
    mana: 243,
    manaReg: 0.7,
    armor: 4.72,
    attackSpeed: 0.62,
    damage: "60‒70",
    moveSpeed: 285,
    attackRange: "melee",
    roles: [
    "Carry",
    "Initiator",
    "Disabler",
    "Durable",
    "Escape"
    ]
    },
    {
    id: 29,
    name: "Sven",
    url: "https://dota2.gamepedia.com/Sven",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/1/1b/Sven_icon.png?version=6afeb3577b8d3e602f7b9cc769cd0be6",
    primaryAttribute: "Strength",
    health: 660,
    healthReg: 2.3,
    mana: 267,
    manaReg: 0.8,
    armor: 4.36,
    attackSpeed: 0.67,
    damage: "66‒68",
    moveSpeed: 310,
    attackRange: "melee",
    roles: [
    "Carry",
    "Disabler",
    "Initiator",
    "Durable",
    "Nuker"
    ]
    },
    {
    id: 30,
    name: "Tidehunter",
    url: "https://dota2.gamepedia.com/Tidehunter",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d5/Tidehunter_icon.png?version=72d689d15e1011f9668c546af5f19f00",
    primaryAttribute: "Strength",
    health: 640,
    healthReg: 2.2,
    mana: 267,
    manaReg: 0.8,
    armor: 2.4,
    attackSpeed: 0.68,
    damage: "47‒53",
    moveSpeed: 300,
    attackRange: "melee",
    roles: [
    "Initiator",
    "Durable",
    "Disabler",
    "Nuker"
    ]
    },
    {
    id: 31,
    name: "Timbersaw",
    url: "https://dota2.gamepedia.com/Timbersaw",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/9/9a/Timbersaw_icon.png?version=8cdae5ee791dccd7b4dd8cf5db327bdd",
    primaryAttribute: "Strength",
    health: 620,
    healthReg: 2.1,
    mana: 351,
    manaReg: 1.15,
    armor: 0.56,
    attackSpeed: 0.68,
    damage: "47‒51",
    moveSpeed: 290,
    attackRange: "melee",
    roles: [
    "Nuker",
    "Durable",
    "Escape"
    ]
    },
    {
    id: 32,
    name: "Tiny",
    url: "https://dota2.gamepedia.com/Tiny",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/5/55/Tiny_icon.png?version=042adfa9c45fb68093cc6fb4cbe06ea8",
    primaryAttribute: "Strength",
    health: 800,
    healthReg: 3,
    mana: 279,
    manaReg: 0.85,
    armor: 0,
    attackSpeed: 0.59,
    damage: "74‒80",
    moveSpeed: 290,
    attackRange: "melee",
    roles: [
    "Carry",
    "Nuker",
    "Pusher",
    "Initiator",
    "Durable",
    "Disabler"
    ]
    },
    {
    id: 33,
    name: "Treant Protector",
    url: "https://dota2.gamepedia.com/Treant_Protector",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/3/3f/Treant_Protector_icon.png?version=d4d85450f31c83aea8266dfd419b70d7",
    primaryAttribute: "Strength",
    health: 700,
    healthReg: 2.5,
    mana: 315,
    manaReg: 1,
    armor: 0.4,
    attackSpeed: 0.61,
    damage: "87‒95",
    moveSpeed: 270,
    attackRange: "melee",
    roles: [
    "Support",
    "Initiator",
    "Durable",
    "Disabler",
    "Escape"
    ]
    },
    {
    id: 34,
    name: "Tusk",
    url: "https://dota2.gamepedia.com/Tusk",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/c/ce/Tusk_icon.png?version=147fb449a87e1067c85f21f186132092",
    primaryAttribute: "Strength",
    health: 660,
    healthReg: 2.3,
    mana: 291,
    manaReg: 0.9,
    armor: 2.68,
    attackSpeed: 0.72,
    damage: "50‒54",
    moveSpeed: 300,
    attackRange: "melee",
    roles: [
    "Initiator",
    "Disabler",
    "Nuker"
    ]
    },
    {
    id: 35,
    name: "Underlord",
    url: "https://dota2.gamepedia.com/Underlord",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/1/18/Underlord_icon.png?version=608e265d917a1cb3ecbdb479ca17cfe9",
    primaryAttribute: "Strength",
    health: 700,
    healthReg: 2.5,
    mana: 279,
    manaReg: 0.85,
    armor: 2.92,
    attackSpeed: 0.66,
    damage: "62‒68",
    moveSpeed: 295,
    attackRange: "melee",
    roles: [
    "Support",
    "Durable",
    "Nuker",
    "Disabler",
    "Escape"
    ]
    },
    {
    id: 36,
    name: "Undying",
    url: "https://dota2.gamepedia.com/Undying",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/6/61/Undying_icon.png?version=60d8f84491097a3128b7bb2a3de26bf7",
    primaryAttribute: "Strength",
    health: 640,
    healthReg: 2.2,
    mana: 399,
    manaReg: 1.35,
    armor: 3.6,
    attackSpeed: 0.65,
    damage: "57‒65",
    moveSpeed: 300,
    attackRange: "melee",
    roles: [
    "Support",
    "Durable",
    "Disabler",
    "Nuker"
    ]
    },
    {
    id: 37,
    name: "Wraith King",
    url: "https://dota2.gamepedia.com/Wraith_King",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/1/1e/Wraith_King_icon.png?version=52212107e602b6a17dfc1d7515086216",
    primaryAttribute: "Strength",
    health: 640,
    healthReg: 2.2,
    mana: 291,
    manaReg: 0.9,
    armor: 1.88,
    attackSpeed: 0.69,
    damage: "61‒63",
    moveSpeed: 315,
    attackRange: "melee",
    roles: [
    "Carry",
    "Support",
    "Durable",
    "Disabler",
    "Initiator"
    ]
    },
    {
    id: 38,
    name: "Anti-Mage",
    url: "https://dota2.gamepedia.com/Anti-Mage",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8e/Anti-Mage_icon.png?version=f55b1d31df2c842ebd3e6121f4dc513d",
    primaryAttribute: "Agility",
    health: 660,
    healthReg: 2.55,
    mana: 219,
    manaReg: 0.6,
    armor: 2.84,
    attackSpeed: 0.89,
    damage: "53‒57",
    moveSpeed: 310,
    attackRange: "melee",
    roles: [
    "Carry",
    "Escape",
    "Nuker"
    ]
    },
    {
    id: 39,
    name: "Arc Warden",
    url: "https://dota2.gamepedia.com/Arc_Warden",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/0/07/Arc_Warden_icon.png?version=7ef22642fb6a42d09bc39601f19818ab",
    primaryAttribute: "Agility",
    health: 700,
    healthReg: 2.75,
    mana: 363,
    manaReg: 1.2,
    armor: 0.4,
    attackSpeed: 0.68,
    damage: "46‒56",
    moveSpeed: 280,
    attackRange: "range",
    roles: [
    "Carry",
    "Escape",
    "Nuker"
    ]
    },
    {
    id: 40,
    name: "Bloodseeker",
    url: "https://dota2.gamepedia.com/Bloodseeker",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/5/56/Bloodseeker_icon.png?version=13fa81ed7d1bf313049de902c91def21",
    primaryAttribute: "Agility",
    health: 680,
    healthReg: 2.4,
    mana: 291,
    manaReg: 0.9,
    armor: 3.84,
    attackSpeed: 0.73,
    damage: "57‒63",
    moveSpeed: 295,
    attackRange: "melee",
    roles: [
    "Carry",
    "Disabler",
    "Jungler",
    "Nuker",
    "Initiator"
    ]
    },
    {
    id: 41,
    name: "Bounty Hunter",
    url: "https://dota2.gamepedia.com/Bounty_Hunter",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a6/Bounty_Hunter_icon.png?version=4a8be8d7f90be0936164013d63f17670",
    primaryAttribute: "Agility",
    health: 600,
    healthReg: 2.5,
    mana: 303,
    manaReg: 0.95,
    armor: 6.36,
    attackSpeed: 0.71,
    damage: "45‒59",
    moveSpeed: 315,
    attackRange: "melee",
    roles: [
    "Escape",
    "Nuker"
    ]
    },
    {
    id: 42,
    name: "Broodmother",
    url: "https://dota2.gamepedia.com/Broodmother",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/d/df/Broodmother_icon.png?version=e5fc8a51578011186b3517e1b64cc72a",
    primaryAttribute: "Agility",
    health: 560,
    healthReg: 1.8,
    mana: 291,
    manaReg: 0.9,
    armor: 2.4,
    attackSpeed: 0.68,
    damage: "44‒50",
    moveSpeed: 275,
    attackRange: "melee",
    roles: [
    "Carry",
    "Pusher",
    "Escape",
    "Nuker"
    ]
    },
    {
    id: 43,
    name: "Clinkz",
    url: "https://dota2.gamepedia.com/Clinkz",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/c/cb/Clinkz_icon.png?version=1764f0e7f6b084058f8e417891e3135e",
    primaryAttribute: "Agility",
    health: 440,
    healthReg: 1.45,
    mana: 291,
    manaReg: 0.9,
    armor: 3.52,
    attackSpeed: 0.72,
    damage: "37‒43",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Carry",
    "Escape",
    "Pusher"
    ]
    },
    {
    id: 44,
    name: "Drow Ranger",
    url: "https://dota2.gamepedia.com/Drow_Ranger",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/8/80/Drow_Ranger_icon.png?version=53f9bde6e8f3c953a752c1358175309a",
    primaryAttribute: "Agility",
    health: 540,
    healthReg: 1.95,
    mana: 255,
    manaReg: 0.75,
    armor: 1.64,
    attackSpeed: 0.76,
    damage: "48‒59",
    moveSpeed: 285,
    attackRange: "range",
    roles: [
    "Carry",
    "Disabler",
    "Pusher"
    ]
    },
    {
    id: 45,
    name: "Ember Spirit",
    url: "https://dota2.gamepedia.com/Ember_Spirit",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/9/91/Ember_Spirit_icon.png?version=d457d8fe38d1aae31d81f6e177d5f802",
    primaryAttribute: "Agility",
    health: 620,
    healthReg: 2.6,
    mana: 315,
    manaReg: 1,
    armor: 3.52,
    attackSpeed: 0.72,
    damage: "55‒59",
    moveSpeed: 305,
    attackRange: "melee",
    roles: [
    "Carry",
    "Escape",
    "Nuker",
    "Disabler",
    "Initiator"
    ]
    },
    {
    id: 46,
    name: "Faceless Void",
    url: "https://dota2.gamepedia.com/Faceless_Void",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/7/73/Faceless_Void_icon.png?version=af7f98a0de5e29bc73b662a27670aa9e",
    primaryAttribute: "Agility",
    health: 680,
    healthReg: 2.9,
    mana: 255,
    manaReg: 0.75,
    armor: 3.68,
    attackSpeed: 0.72,
    damage: "56‒62",
    moveSpeed: 300,
    attackRange: "melee",
    roles: [
    "Carry",
    "Initiator",
    "Disabler",
    "Escape",
    "Durable"
    ]
    },
    {
    id: 47,
    name: "Gyrocopter",
    url: "https://dota2.gamepedia.com/Gyrocopter",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/4/4f/Gyrocopter_icon.png?version=f24686d2d018218824e5dc17c3e4dca1",
    primaryAttribute: "Agility",
    health: 640,
    healthReg: 2.2,
    mana: 303,
    manaReg: 0.95,
    armor: 5.04,
    attackSpeed: 0.7,
    damage: "40‒50",
    moveSpeed: 315,
    attackRange: "range",
    roles: [
    "Carry",
    "Nuker",
    "Disabler"
    ]
    },
    {
    id: 48,
    name: "Juggernaut",
    url: "https://dota2.gamepedia.com/Juggernaut",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/0/03/Juggernaut_icon.png?version=728e72d86473fed502ade52c7326d544",
    primaryAttribute: "Agility",
    health: 620,
    healthReg: 2.6,
    mana: 243,
    manaReg: 0.7,
    armor: 5.76,
    attackSpeed: 0.97,
    damage: "48‒52",
    moveSpeed: 300,
    attackRange: "melee",
    roles: [
    "Carry",
    "Pusher",
    "Escape"
    ]
    },
    {
    id: 49,
    name: "Lone Druid",
    url: "https://dota2.gamepedia.com/Lone_Druid",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/5/5d/Lone_Druid_icon.png?version=f9e25298afe665f5bcb1cbd3f22b828c",
    primaryAttribute: "Agility",
    health: 560,
    healthReg: 2.05,
    mana: 231,
    manaReg: 0.65,
    armor: 1.2,
    attackSpeed: 0.71,
    damage: "38‒42",
    moveSpeed: 325,
    attackRange: "range",
    roles: [
    "Carry",
    "Pusher",
    "Jungler",
    "Durable"
    ]
    },
    {
    id: 50,
    name: "Luna",
    url: "https://dota2.gamepedia.com/Luna",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7d/Luna_icon.png?version=b1d1b20a5c17defc097201e30e83ff98",
    primaryAttribute: "Agility",
    health: 520,
    healthReg: 1.6,
    mana: 267,
    manaReg: 0.8,
    armor: 2.88,
    attackSpeed: 0.69,
    damage: "38‒44",
    moveSpeed: 325,
    attackRange: "range",
    roles: [
    "Carry",
    "Nuker",
    "Pusher"
    ]
    },
    {
    id: 51,
    name: "Medusa",
    url: "https://dota2.gamepedia.com/Medusa",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/c/cc/Medusa_icon.png?version=3d9ae4d87d7dd18473b0077c6d51d3d3",
    primaryAttribute: "Agility",
    health: 500,
    healthReg: 1.5,
    mana: 303,
    manaReg: 0.95,
    armor: 2.52,
    attackSpeed: 0.72,
    damage: "46‒52",
    moveSpeed: 275,
    attackRange: "range",
    roles: [
    "Carry",
    "Disabler",
    "Durable"
    ]
    },
    {
    id: 52,
    name: "Meepo",
    url: "https://dota2.gamepedia.com/Meepo",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/8/85/Meepo_icon.png?version=06970686c2620e4899376b9ee7e17d47",
    primaryAttribute: "Agility",
    health: 680,
    healthReg: 2.65,
    mana: 315,
    manaReg: 1,
    armor: 6.84,
    attackSpeed: 0.73,
    damage: "44‒50",
    moveSpeed: 330,
    attackRange: "melee",
    roles: [
    "Carry",
    "Escape",
    "Nuker",
    "Disabler",
    "Initiator",
    "Pusher"
    ]
    },
    {
    id: 53,
    name: "Mirana",
    url: "https://dota2.gamepedia.com/Mirana",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/1/12/Mirana_icon.png?version=a80affcf57d37d4fe5d898cd7e3f4e0a",
    primaryAttribute: "Agility",
    health: 560,
    healthReg: 1.8,
    mana: 303,
    manaReg: 0.95,
    armor: 1.88,
    attackSpeed: 0.69,
    damage: "43‒48",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Carry",
    "Support",
    "Escape",
    "Nuker",
    "Disabler"
    ]
    },
    {
    id: 54,
    name: "Monkey King",
    url: "https://dota2.gamepedia.com/Monkey_King",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7b/Monkey_King_icon.png?version=abe10431bbc2211c3e4f931534bd3d27",
    primaryAttribute: "Agility",
    health: 580,
    healthReg: 3.4,
    mana: 315,
    manaReg: 1,
    armor: 0.52,
    attackSpeed: 0.72,
    damage: "51‒57",
    moveSpeed: 305,
    attackRange: "melee",
    roles: [
    "Carry",
    "Escape",
    "Disabler",
    "Initiator"
    ]
    },
    {
    id: 55,
    name: "Morphling",
    url: "https://dota2.gamepedia.com/Morphling",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7b/Morphling_icon.png?version=d1015dea93a88152e3fef62e9b64ad6e",
    primaryAttribute: "Agility",
    health: 600,
    healthReg: 2,
    mana: 231,
    manaReg: 0.65,
    armor: 1.84,
    attackSpeed: 0.83,
    damage: "33‒42",
    moveSpeed: 280,
    attackRange: "range",
    roles: [
    "Carry",
    "Escape",
    "Durable",
    "Nuker",
    "Disabler"
    ]
    },
    {
    id: 56,
    name: "Naga Siren",
    url: "https://dota2.gamepedia.com/Naga_Siren",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/6/60/Naga_Siren_icon.png?version=a64bc31b30d125ba993f6498b68f9a0b",
    primaryAttribute: "Agility",
    health: 640,
    healthReg: 3.7,
    mana: 327,
    manaReg: 1.05,
    armor: 6.36,
    attackSpeed: 0.71,
    damage: "44‒46",
    moveSpeed: 320,
    attackRange: "melee",
    roles: [
    "Carry",
    "Support",
    "Pusher",
    "Disabler",
    "Initiator",
    "Escape"
    ]
    },
    {
    id: 57,
    name: "Nyx Assassin",
    url: "https://dota2.gamepedia.com/Nyx_Assassin",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/f/fa/Nyx_Assassin_icon.png?version=82c807740fa60d9ab486e0bf0e4153c2",
    primaryAttribute: "Agility",
    health: 580,
    healthReg: 5.15,
    mana: 291,
    manaReg: 0.9,
    armor: 4.04,
    attackSpeed: 0.7,
    damage: "46‒50",
    moveSpeed: 305,
    attackRange: "melee",
    roles: [
    "Disabler",
    "Nuker",
    "Initiator",
    "Escape"
    ]
    },
    {
    id: 58,
    name: "Pangolier",
    url: "https://dota2.gamepedia.com/Pangolier",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/4/4e/Pangolier_icon.png?version=0ca9284b8283c2fbd8550b2be5fd9c3a",
    primaryAttribute: "Agility",
    health: 540,
    healthReg: 1.95,
    mana: 267,
    manaReg: 0.8,
    armor: 3.88,
    attackSpeed: 0.69,
    damage: "51‒57",
    moveSpeed: 305,
    attackRange: "melee",
    roles: [
    "Carry",
    "Nuker",
    "Disabler",
    "Durable",
    "Escape",
    "Initiator"
    ]
    },
    {
    id: 59,
    name: "Phantom Assassin",
    url: "https://dota2.gamepedia.com/Phantom_Assassin",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8e/Phantom_Assassin_icon.png?version=fcf1444e78efa7c35c74f98e934c271d",
    primaryAttribute: "Agility",
    health: 620,
    healthReg: 2.35,
    mana: 255,
    manaReg: 0.75,
    armor: 4.68,
    attackSpeed: 0.72,
    damage: "46‒48",
    moveSpeed: 305,
    attackRange: "melee",
    roles: [
    "Carry",
    "Escape"
    ]
    },
    {
    id: 60,
    name: "Phantom Lancer",
    url: "https://dota2.gamepedia.com/Phantom_Lancer",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/8/81/Phantom_Lancer_icon.png?version=a78af53d50a56dff0aede90622eb3511",
    primaryAttribute: "Agility",
    health: 580,
    healthReg: 3.4,
    mana: 303,
    manaReg: 0.95,
    armor: 4.64,
    attackSpeed: 0.76,
    damage: "51‒73",
    moveSpeed: 290,
    attackRange: "melee",
    roles: [
    "Carry",
    "Escape",
    "Pusher",
    "Nuker"
    ]
    },
    {
    id: 61,
    name: "Razor",
    url: "https://dota2.gamepedia.com/Razor",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/6/66/Razor_icon.png?version=0146a218be9881bb9d75b19ed14d35be",
    primaryAttribute: "Agility",
    health: 640,
    healthReg: 2.2,
    mana: 327,
    manaReg: 1.05,
    armor: 2.52,
    attackSpeed: 0.72,
    damage: "45‒47",
    moveSpeed: 285,
    attackRange: "range",
    roles: [
    "Carry",
    "Durable",
    "Nuker",
    "Pusher"
    ]
    },
    {
    id: 62,
    name: "Riki",
    url: "https://dota2.gamepedia.com/Riki",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7d/Riki_icon.png?version=85a963fecc5bdfc702aa22d6314eb728",
    primaryAttribute: "Agility",
    health: 560,
    healthReg: 4.8,
    mana: 243,
    manaReg: 0.7,
    armor: 5.8,
    attackSpeed: 0.76,
    damage: "48‒52",
    moveSpeed: 290,
    attackRange: "melee",
    roles: [
    "Carry",
    "Escape",
    "Disabler"
    ]
    },
    {
    id: 63,
    name: "Shadow Fiend",
    url: "https://dota2.gamepedia.com/Shadow_Fiend",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/3/36/Shadow_Fiend_icon.png?version=aead4589c97b4c486ca808225004b114",
    primaryAttribute: "Agility",
    health: 580,
    healthReg: 2.15,
    mana: 291,
    manaReg: 0.9,
    armor: 3.2,
    attackSpeed: 0.71,
    damage: "35‒41",
    moveSpeed: 305,
    attackRange: "range",
    roles: [
    "Carry",
    "Nuker"
    ]
    },
    {
    id: 64,
    name: "Slark",
    url: "https://dota2.gamepedia.com/Slark",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/a/aa/Slark_icon.png?version=18b68c91671452beab47ca1813e1366e",
    primaryAttribute: "Agility",
    health: 620,
    healthReg: 3.85,
    mana: 267,
    manaReg: 0.8,
    armor: 3.36,
    attackSpeed: 0.71,
    damage: "54‒62",
    moveSpeed: 300,
    attackRange: "melee",
    roles: [
    "Carry",
    "Escape",
    "Disabler",
    "Nuker"
    ]
    },
    {
    id: 65,
    name: "Sniper",
    url: "https://dota2.gamepedia.com/Sniper",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/5/51/Sniper_icon.png?version=6429ecb9ebbc59abed6b846ac0af6f0d",
    primaryAttribute: "Agility",
    health: 580,
    healthReg: 1.9,
    mana: 255,
    manaReg: 0.75,
    armor: 2.36,
    attackSpeed: 0.71,
    damage: "36‒42",
    moveSpeed: 285,
    attackRange: "range",
    roles: [
    "Carry",
    "Nuker"
    ]
    },
    {
    id: 66,
    name: "Spectre",
    url: "https://dota2.gamepedia.com/Spectre",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/f/ff/Spectre_icon.png?version=8af2c21961605d25cfa1be31725d7422",
    primaryAttribute: "Agility",
    health: 660,
    healthReg: 2.3,
    mana: 267,
    manaReg: 0.8,
    armor: 3.68,
    attackSpeed: 0.72,
    damage: "46‒50",
    moveSpeed: 290,
    attackRange: "melee",
    roles: [
    "Carry",
    "Durable",
    "Escape"
    ]
    },
    {
    id: 67,
    name: "Templar Assassin",
    url: "https://dota2.gamepedia.com/Templar_Assassin",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/9/9c/Templar_Assassin_icon.png?version=e531fd05354743719c1b8dd48dc108d5",
    primaryAttribute: "Agility",
    health: 580,
    healthReg: 2.15,
    mana: 315,
    manaReg: 1,
    armor: 4.68,
    attackSpeed: 0.72,
    damage: "53‒59",
    moveSpeed: 305,
    attackRange: "melee",
    roles: [
    "Carry",
    "Escape"
    ]
    },
    {
    id: 68,
    name: "Terrorblade",
    url: "https://dota2.gamepedia.com/Terrorblade",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/5/52/Terrorblade_icon.png?version=77a3768fe6b0ad17bb407b12d6479d1d",
    primaryAttribute: "Agility",
    health: 500,
    healthReg: 1.5,
    mana: 303,
    manaReg: 0.95,
    armor: 10.52,
    attackSpeed: 0.81,
    damage: "48‒54",
    moveSpeed: 310,
    attackRange: "melee",
    roles: [
    "Carry",
    "Pusher",
    "Nuker"
    ]
    },
    {
    id: 69,
    name: "Troll Warlord",
    url: "https://dota2.gamepedia.com/Troll_Warlord",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/f/f0/Troll_Warlord_icon.png?version=43c7aadede7bd18591b0c6dbb7dbd027",
    primaryAttribute: "Agility",
    health: 620,
    healthReg: 2.35,
    mana: 231,
    manaReg: 0.65,
    armor: 2.36,
    attackSpeed: 0.71,
    damage: "44‒56",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Carry",
    "Pusher",
    "Disabler",
    "Durable"
    ]
    },
    {
    id: 70,
    name: "Ursa",
    url: "https://dota2.gamepedia.com/Ursa",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/4/40/Ursa_icon.png?version=6a015dc9739ae708a62230a0cea9ffa6",
    primaryAttribute: "Agility",
    health: 680,
    healthReg: 2.9,
    mana: 267,
    manaReg: 0.8,
    armor: 4.88,
    attackSpeed: 0.69,
    damage: "42‒46",
    moveSpeed: 325,
    attackRange: "melee",
    roles: [
    "Carry",
    "Jungler",
    "Durable",
    "Disabler"
    ]
    },
    {
    id: 71,
    name: "Vengeful Spirit",
    url: "https://dota2.gamepedia.com/Vengeful_Spirit",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/2/20/Vengeful_Spirit_icon.png?version=f7b24acba1c0bf726248ca1dd4620c7c",
    primaryAttribute: "Agility",
    health: 580,
    healthReg: 2.15,
    mana: 231,
    manaReg: 0.65,
    armor: 4.32,
    attackSpeed: 0.75,
    damage: "39‒47",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Support",
    "Initiator",
    "Disabler",
    "Nuker",
    "Escape"
    ]
    },
    {
    id: 72,
    name: "Venomancer",
    url: "https://dota2.gamepedia.com/Venomancer",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/2/25/Venomancer_icon.png?version=52d85a454dde46581873c15b7a072237",
    primaryAttribute: "Agility",
    health: 580,
    healthReg: 1.9,
    mana: 279,
    manaReg: 0.85,
    armor: 4.16,
    attackSpeed: 0.74,
    damage: "42‒44",
    moveSpeed: 275,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker",
    "Initiator",
    "Pusher",
    "Disabler"
    ]
    },
    {
    id: 73,
    name: "Viper",
    url: "https://dota2.gamepedia.com/Viper",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/5/5f/Viper_icon.png?version=2a8187ea6747e352093e1e54bc2606ff",
    primaryAttribute: "Agility",
    health: 620,
    healthReg: 2.1,
    mana: 255,
    manaReg: 0.75,
    armor: 1.36,
    attackSpeed: 0.71,
    damage: "44‒46",
    moveSpeed: 275,
    attackRange: "range",
    roles: [
    "Carry",
    "Durable",
    "Initiator",
    "Disabler"
    ]
    },
    {
    id: 74,
    name: "Weaver",
    url: "https://dota2.gamepedia.com/Weaver",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/0/09/Weaver_icon.png?version=09f9240a75d1045d5d403385c61db35c",
    primaryAttribute: "Agility",
    health: 520,
    healthReg: 2.6,
    mana: 231,
    manaReg: 0.65,
    armor: 1.24,
    attackSpeed: 0.63,
    damage: "50‒60",
    moveSpeed: 275,
    attackRange: "range",
    roles: [
    "Carry",
    "Escape"
    ]
    },
    {
    id: 75,
    name: "Ancient Apparition",
    url: "https://dota2.gamepedia.com/Ancient_Apparition",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/6/67/Ancient_Apparition_icon.png?version=4ca8ab4fcec9d410c544a9938b521d50",
    primaryAttribute: "Intelligence",
    health: 600,
    healthReg: 2,
    mana: 351,
    manaReg: 1.15,
    armor: 2.2,
    attackSpeed: 0.71,
    damage: "44‒54",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Support",
    "Disabler",
    "Nuker"
    ]
    },
    {
    id: 76,
    name: "Bane",
    url: "https://dota2.gamepedia.com/Bane",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c3/Bane_icon.png?version=377fefe5af50310f8cff4fe94a093261",
    primaryAttribute: "Intelligence",
    health: 660,
    healthReg: 2.3,
    mana: 351,
    manaReg: 1.15,
    armor: 4.68,
    attackSpeed: 0.72,
    damage: "58‒64",
    moveSpeed: 305,
    attackRange: "range",
    roles: [
    "Support",
    "Disabler",
    "Nuker",
    "Durable"
    ]
    },
    {
    id: 77,
    name: "Batrider",
    url: "https://dota2.gamepedia.com/Batrider",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/f/f2/Batrider_icon.png?version=9bcaca9957e859c2aa8656b2dad2ef1c",
    primaryAttribute: "Intelligence",
    health: 760,
    healthReg: 4.55,
    mana: 339,
    manaReg: 1.1,
    armor: 2.4,
    attackSpeed: 0.68,
    damage: "38‒42",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Initiator",
    "Jungler",
    "Disabler",
    "Escape"
    ]
    },
    {
    id: 78,
    name: "Chen",
    url: "https://dota2.gamepedia.com/Chen",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/6/61/Chen_icon.png?version=0f827938b63d647d266ce8f613c832ed",
    primaryAttribute: "Intelligence",
    health: 700,
    healthReg: 2.5,
    mana: 303,
    manaReg: 0.95,
    armor: 1.4,
    attackSpeed: 0.68,
    damage: "48‒58",
    moveSpeed: 305,
    attackRange: "range",
    roles: [
    "Support",
    "Jungler",
    "Pusher"
    ]
    },
    {
    id: 79,
    name: "Crystal Maiden",
    url: "https://dota2.gamepedia.com/Crystal_Maiden",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/2/27/Crystal_Maiden_icon.png?version=1fe64eb25bb59c8f5f9b916a8ee5f378",
    primaryAttribute: "Intelligence",
    health: 560,
    healthReg: 1.8,
    mana: 243,
    manaReg: 0.7,
    armor: 2.56,
    attackSpeed: 0.68,
    damage: "44‒50",
    moveSpeed: 275,
    attackRange: "range",
    roles: [
    "Support",
    "Disabler",
    "Nuker",
    "Jungler"
    ]
    },
    {
    id: 80,
    name: "Dark Seer",
    url: "https://dota2.gamepedia.com/Dark_Seer",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c5/Dark_Seer_icon.png?version=9b81b657518099522d6a36b5cdd51e7e",
    primaryAttribute: "Intelligence",
    health: 680,
    healthReg: 2.4,
    mana: 327,
    manaReg: 1.05,
    armor: 4.92,
    attackSpeed: 0.66,
    damage: "54‒60",
    moveSpeed: 300,
    attackRange: "melee",
    roles: [
    "Initiator",
    "Jungler",
    "Escape",
    "Disabler"
    ]
    },
    {
    id: 81,
    name: "Dark Willow",
    url: "https://dota2.gamepedia.com/Dark_Willow",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/3/3c/Dark_Willow_icon.png?version=a4ef3ff9c27f1f5510f20e8dec1f15a9",
    primaryAttribute: "Intelligence",
    health: 600,
    healthReg: 2,
    mana: 291,
    manaReg: 0.9,
    armor: 1.88,
    attackSpeed: 0.91,
    damage: "45‒53",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker",
    "Disabler",
    "Escape"
    ]
    },
    {
    id: 82,
    name: "Dazzle",
    url: "https://dota2.gamepedia.com/Dazzle",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/e/e6/Dazzle_icon.png?version=12e839c1ea458185e87dcf7a7c02c0e6",
    primaryAttribute: "Intelligence",
    health: 560,
    healthReg: 1.8,
    mana: 375,
    manaReg: 1.25,
    armor: 2.36,
    attackSpeed: 0.71,
    damage: "47‒53",
    moveSpeed: 305,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker",
    "Disabler"
    ]
    },
    {
    id: 83,
    name: "Death Prophet",
    url: "https://dota2.gamepedia.com/Death_Prophet",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d7/Death_Prophet_icon.png?version=4010d86b2e5761cac55c24b259696f34",
    primaryAttribute: "Intelligence",
    health: 580,
    healthReg: 1.9,
    mana: 327,
    manaReg: 1.05,
    armor: 2.24,
    attackSpeed: 0.67,
    damage: "50‒62",
    moveSpeed: 310,
    attackRange: "range",
    roles: [
    "Carry",
    "Pusher",
    "Nuker",
    "Disabler"
    ]
    },
    {
    id: 84,
    name: "Disruptor",
    url: "https://dota2.gamepedia.com/Disruptor",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/9/97/Disruptor_icon.png?version=075011a1621b2d1750e4919e09c25b0e",
    primaryAttribute: "Intelligence",
    health: 620,
    healthReg: 2.1,
    mana: 315,
    manaReg: 1,
    armor: 2.4,
    attackSpeed: 0.68,
    damage: "49‒53",
    moveSpeed: 295,
    attackRange: "range",
    roles: [
    "Support",
    "Disabler",
    "Nuker",
    "Initiator"
    ]
    },
    {
    id: 85,
    name: "Enchantress",
    url: "https://dota2.gamepedia.com/Enchantress",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/4/41/Enchantress_icon.png?version=098b08695e2d972fb667dd4509e74ed5",
    primaryAttribute: "Intelligence",
    health: 540,
    healthReg: 1.7,
    mana: 303,
    manaReg: 0.95,
    armor: 3.04,
    attackSpeed: 0.7,
    damage: "49‒59",
    moveSpeed: 315,
    attackRange: "range",
    roles: [
    "Support",
    "Jungler",
    "Pusher",
    "Durable",
    "Disabler"
    ]
    },
    {
    id: 86,
    name: "Enigma",
    url: "https://dota2.gamepedia.com/Enigma",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/f/f7/Enigma_icon.png?version=cd786d109fe3b9bbf88f82ad48c8723b",
    primaryAttribute: "Intelligence",
    health: 620,
    healthReg: 2.1,
    mana: 291,
    manaReg: 0.9,
    armor: 4.24,
    attackSpeed: 0.67,
    damage: "42‒48",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Disabler",
    "Jungler",
    "Initiator",
    "Pusher"
    ]
    },
    {
    id: 87,
    name: "Grimstroke",
    url: "https://dota2.gamepedia.com/Grimstroke",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d7/Grimstroke_icon.png?version=615a597828869dbf570f7993c3f927bc",
    primaryAttribute: "Intelligence",
    health: 620,
    healthReg: 2.1,
    mana: 351,
    manaReg: 1.15,
    armor: 2.88,
    attackSpeed: 0.69,
    damage: "50‒54",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker",
    "Disabler",
    "Escape"
    ]
    },
    {
    id: 88,
    name: "Invoker",
    url: "https://dota2.gamepedia.com/Invoker",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/0/00/Invoker_icon.png?version=fb7516f0b780535fa8acfa9e8cb99266",
    primaryAttribute: "Intelligence",
    health: 560,
    healthReg: 1.8,
    mana: 243,
    manaReg: 0.7,
    armor: 1.24,
    attackSpeed: 0.67,
    damage: "38‒44",
    moveSpeed: 280,
    attackRange: "range",
    roles: [
    "Carry",
    "Nuker",
    "Disabler",
    "Escape",
    "Pusher"
    ]
    },
    {
    id: 89,
    name: "Jakiro",
    url: "https://dota2.gamepedia.com/Jakiro",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/2/2f/Jakiro_icon.png?version=c4f2df2b9c444557b75aee31f289f8cf",
    primaryAttribute: "Intelligence",
    health: 740,
    healthReg: 2.7,
    mana: 387,
    manaReg: 1.3,
    armor: 2.6,
    attackSpeed: 0.65,
    damage: "53‒61",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker",
    "Pusher",
    "Disabler"
    ]
    },
    {
    id: 90,
    name: "Keeper of the Light",
    url: "https://dota2.gamepedia.com/Keeper_of_the_Light",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/b/b9/Keeper_of_the_Light_icon.png?version=134e16d0dd565e2763fd2111fe83f439",
    primaryAttribute: "Intelligence",
    health: 520,
    healthReg: 1.6,
    mana: 351,
    manaReg: 1.15,
    armor: 1.4,
    attackSpeed: 0.68,
    damage: "43‒50",
    moveSpeed: 330,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker",
    "Disabler",
    "Jungler"
    ]
    },
    {
    id: 91,
    name: "Leshrac",
    url: "https://dota2.gamepedia.com/Leshrac",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/2/26/Leshrac_icon.png?version=fa8d18a43365db435910db186eb985d5",
    primaryAttribute: "Intelligence",
    health: 560,
    healthReg: 1.8,
    mana: 339,
    manaReg: 1.1,
    armor: 3.68,
    attackSpeed: 0.72,
    damage: "41‒45",
    moveSpeed: 325,
    attackRange: "range",
    roles: [
    "Carry",
    "Support",
    "Nuker",
    "Pusher",
    "Disabler"
    ]
    },
    {
    id: 92,
    name: "Lich",
    url: "https://dota2.gamepedia.com/Lich",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/b/bb/Lich_icon.png?version=7cb34de5d2bb15610cda9474d6c1b306",
    primaryAttribute: "Intelligence",
    health: 600,
    healthReg: 2,
    mana: 315,
    manaReg: 1,
    armor: 1.4,
    attackSpeed: 0.68,
    damage: "46‒55",
    moveSpeed: 295,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker"
    ]
    },
    {
    id: 93,
    name: "Lina",
    url: "https://dota2.gamepedia.com/Lina",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/3/35/Lina_icon.png?version=2bc137c161b17cd86674d29d0a0ed261",
    primaryAttribute: "Intelligence",
    health: 600,
    healthReg: 2,
    mana: 435,
    manaReg: 1.5,
    armor: 4.68,
    attackSpeed: 0.77,
    damage: "51‒63",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Support",
    "Carry",
    "Nuker",
    "Disabler"
    ]
    },
    {
    id: 94,
    name: "Lion",
    url: "https://dota2.gamepedia.com/Lion",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/b/b8/Lion_icon.png?version=7d730dc2fc5c3b86db8f84f9e09d1de2",
    primaryAttribute: "Intelligence",
    health: 560,
    healthReg: 1.8,
    mana: 291,
    manaReg: 0.9,
    armor: 1.4,
    attackSpeed: 0.68,
    damage: "47‒53",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Support",
    "Disabler",
    "Nuker",
    "Initiator"
    ]
    },
    {
    id: 95,
    name: "Nature's Prophet",
    url: "https://dota2.gamepedia.com/Nature%27s_Prophet",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c4/Nature%27s_Prophet_icon.png?version=3d5a7a42e57a7e43f058e8d0874cda03",
    primaryAttribute: "Intelligence",
    health: 620,
    healthReg: 2.1,
    mana: 351,
    manaReg: 1.15,
    armor: 4.88,
    attackSpeed: 0.69,
    damage: "52‒66",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Carry",
    "Jungler",
    "Pusher",
    "Escape",
    "Nuker"
    ]
    },
    {
    id: 96,
    name: "Necrophos",
    url: "https://dota2.gamepedia.com/Necrophos",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a6/Necrophos_icon.png?version=ddc8b2eab62f4e578045623bfc74bd0b",
    primaryAttribute: "Intelligence",
    health: 560,
    healthReg: 1.8,
    mana: 315,
    manaReg: 1,
    armor: 2.92,
    attackSpeed: 0.66,
    damage: "46‒50",
    moveSpeed: 280,
    attackRange: "range",
    roles: [
    "Carry",
    "Nuker",
    "Durable",
    "Disabler"
    ]
    },
    {
    id: 97,
    name: "Ogre Magi",
    url: "https://dota2.gamepedia.com/Ogre_Magi",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/e/e0/Ogre_Magi_icon.png?version=3fa5ac15939733f3cfddc00aba633795",
    primaryAttribute: "Intelligence",
    health: 700,
    healthReg: 5.75,
    mana: 255,
    manaReg: 0.75,
    armor: 8.24,
    attackSpeed: 0.67,
    damage: "58‒64",
    moveSpeed: 290,
    attackRange: "melee",
    roles: [
    "Support",
    "Nuker",
    "Disabler",
    "Durable",
    "Initiator"
    ]
    },
    {
    id: 98,
    name: "Oracle",
    url: "https://dota2.gamepedia.com/Oracle",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/7/72/Oracle_icon.png?version=50cfbd6e98b026808a9f8ad253605cfa",
    primaryAttribute: "Intelligence",
    health: 600,
    healthReg: 2,
    mana: 327,
    manaReg: 1.05,
    armor: 2.4,
    attackSpeed: 0.82,
    damage: "39‒45",
    moveSpeed: 300,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker",
    "Disabler",
    "Escape"
    ]
    },
    {
    id: 99,
    name: "Outworld Devourer",
    url: "https://dota2.gamepedia.com/Outworld_Devourer",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/9/99/Outworld_Devourer_icon.png?version=bb656970d69f3027d26943bc24b03610",
    primaryAttribute: "Intelligence",
    health: 580,
    healthReg: 1.9,
    mana: 411,
    manaReg: 1.4,
    armor: 5.34,
    attackSpeed: 0.73,
    damage: "44‒59",
    moveSpeed: 310,
    attackRange: "range",
    roles: [
    "Carry",
    "Nuker",
    "Disabler"
    ]
    },
    {
    id: 100,
    name: "Puck",
    url: "https://dota2.gamepedia.com/Puck",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/1/13/Puck_icon.png?version=07290c7498433bde0a87c330a51081c1",
    primaryAttribute: "Intelligence",
    health: 540,
    healthReg: 1.7,
    mana: 351,
    manaReg: 1.15,
    armor: 2.52,
    attackSpeed: 0.72,
    damage: "53‒64",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Initiator",
    "Disabler",
    "Escape",
    "Nuker"
    ]
    },
    {
    id: 101,
    name: "Pugna",
    url: "https://dota2.gamepedia.com/Pugna",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/c/cd/Pugna_icon.png?version=6e8e11c6c2013546664a8251d52e0e97",
    primaryAttribute: "Intelligence",
    health: 580,
    healthReg: 1.9,
    mana: 363,
    manaReg: 1.2,
    armor: 2.56,
    attackSpeed: 0.68,
    damage: "43‒51",
    moveSpeed: 330,
    attackRange: "range",
    roles: [
    "Nuker",
    "Pusher"
    ]
    },
    {
    id: 102,
    name: "Queen of Pain",
    url: "https://dota2.gamepedia.com/Queen_of_Pain",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a1/Queen_of_Pain_icon.png?version=d223991a573549d25a93703234869960",
    primaryAttribute: "Intelligence",
    health: 560,
    healthReg: 1.8,
    mana: 375,
    manaReg: 1.25,
    armor: 3.52,
    attackSpeed: 0.81,
    damage: "45‒53",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "semi-carry",
    "Carry",
    "Nuker",
    "Escape"
    ]
    },
    {
    id: 103,
    name: "Rubick",
    url: "https://dota2.gamepedia.com/Rubick",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8a/Rubick_icon.png?version=069f44c919f07acd1dec09aa71330568",
    primaryAttribute: "Intelligence",
    health: 620,
    healthReg: 2.1,
    mana: 375,
    manaReg: 1.25,
    armor: 2.04,
    attackSpeed: 0.7,
    damage: "47‒57",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Support",
    "Disabler",
    "Nuker"
    ]
    },
    {
    id: 104,
    name: "Shadow Demon",
    url: "https://dota2.gamepedia.com/Shadow_Demon",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/f/f3/Shadow_Demon_icon.png?version=d4f43f79f2752f89c5d1177dae20c2d2",
    primaryAttribute: "Intelligence",
    health: 660,
    healthReg: 2.3,
    mana: 327,
    manaReg: 1.05,
    armor: 2.88,
    attackSpeed: 0.69,
    damage: "50‒54",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Support",
    "Disabler",
    "Initiator",
    "Nuker"
    ]
    },
    {
    id: 105,
    name: "Shadow Shaman",
    url: "https://dota2.gamepedia.com/Shadow_Shaman",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/9/96/Shadow_Shaman_icon.png?version=412ef19dc4b14ec00e5be48a2f3ffa58",
    primaryAttribute: "Intelligence",
    health: 660,
    healthReg: 2.3,
    mana: 303,
    manaReg: 0.95,
    armor: 3.56,
    attackSpeed: 0.68,
    damage: "71‒78",
    moveSpeed: 285,
    attackRange: "range",
    roles: [
    "Support",
    "Pusher",
    "Disabler",
    "Nuker",
    "Initiator"
    ]
    },
    {
    id: 106,
    name: "Silencer",
    url: "https://dota2.gamepedia.com/Silencer",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/9/9f/Silencer_icon.png?version=987250b53e9d354e7385f2b30263730d",
    primaryAttribute: "Intelligence",
    health: 580,
    healthReg: 1.9,
    mana: 375,
    manaReg: 1.25,
    armor: 2.52,
    attackSpeed: 0.72,
    damage: "43‒57",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Carry",
    "Support",
    "Disabler",
    "Initiator",
    "Nuker"
    ]
    },
    {
    id: 107,
    name: "Skywrath Mage",
    url: "https://dota2.gamepedia.com/Skywrath_Mage",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/b/bf/Skywrath_Mage_icon.png?version=e80bcf3140a08fd474e4ae959c68b5bd",
    primaryAttribute: "Intelligence",
    health: 620,
    healthReg: 2.1,
    mana: 375,
    manaReg: 1.25,
    armor: 0.08,
    attackSpeed: 0.66,
    damage: "39‒49",
    moveSpeed: 325,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker",
    "Disabler"
    ]
    },
    {
    id: 108,
    name: "Storm Spirit",
    url: "https://dota2.gamepedia.com/Storm_Spirit",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/1/13/Storm_Spirit_icon.png?version=c9eb4d9152a61c7663cefaa20bc1a8e8",
    primaryAttribute: "Intelligence",
    health: 620,
    healthReg: 2.1,
    mana: 351,
    manaReg: 1.15,
    armor: 5.52,
    attackSpeed: 0.72,
    damage: "49‒59",
    moveSpeed: 285,
    attackRange: "range",
    roles: [
    "Carry",
    "Escape",
    "Nuker",
    "Initiator",
    "Disabler"
    ]
    },
    {
    id: 109,
    name: "Techies",
    url: "https://dota2.gamepedia.com/Techies",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/f/fa/Techies_icon.png?version=156b828f72a516c4327906e03e0c3a0e",
    primaryAttribute: "Intelligence",
    health: 580,
    healthReg: 1.9,
    mana: 339,
    manaReg: 1.1,
    armor: 7.24,
    attackSpeed: 0.67,
    damage: "31‒33",
    moveSpeed: 310,
    attackRange: "range",
    roles: [
    "Nuker",
    "Disabler"
    ]
    },
    {
    id: 110,
    name: "Tinker",
    url: "https://dota2.gamepedia.com/Tinker",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d1/Tinker_icon.png?version=e904d8e318ae448d4639a6ca85303fe6",
    primaryAttribute: "Intelligence",
    health: 540,
    healthReg: 1.7,
    mana: 411,
    manaReg: 1.4,
    armor: 4.08,
    attackSpeed: 0.66,
    damage: "52‒58",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Carry",
    "Nuker",
    "Pusher"
    ]
    },
    {
    id: 111,
    name: "Visage",
    url: "https://dota2.gamepedia.com/Visage",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/9/9e/Visage_icon.png?version=737c2387430a431a85ffd08b7252fb6e",
    primaryAttribute: "Intelligence",
    health: 640,
    healthReg: 2.2,
    mana: 339,
    manaReg: 1.1,
    armor: -0.24,
    attackSpeed: 0.65,
    damage: "45‒55",
    moveSpeed: 285,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker",
    "Durable",
    "Disabler",
    "Pusher"
    ]
    },
    {
    id: 112,
    name: "Warlock",
    url: "https://dota2.gamepedia.com/Warlock",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/3/3f/Warlock_icon.png?version=553c91bae27fe106872f09f7c5da3878",
    primaryAttribute: "Intelligence",
    health: 720,
    healthReg: 2.6,
    mana: 375,
    manaReg: 1.25,
    armor: 2.6,
    attackSpeed: 0.65,
    damage: "49‒59",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Support",
    "Initiator",
    "Disabler"
    ]
    },
    {
    id: 113,
    name: "Windranger",
    url: "https://dota2.gamepedia.com/Windranger",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/6/60/Windranger_icon.png?version=85593ee15f958babcf2f2d1ceb7a3940",
    primaryAttribute: "Intelligence",
    health: 560,
    healthReg: 1.8,
    mana: 291,
    manaReg: 0.9,
    armor: 1.72,
    attackSpeed: 0.78,
    damage: "42‒54",
    moveSpeed: 290,
    attackRange: "range",
    roles: [
    "Carry",
    "Support",
    "Disabler",
    "Escape",
    "Nuker"
    ]
    },
    {
    id: 114,
    name: "Winter Wyvern",
    url: "https://dota2.gamepedia.com/Winter_Wyvern",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/4/4a/Winter_Wyvern_icon.png?version=708c1aac73eef23b9b9183d47484e7b2",
    primaryAttribute: "Intelligence",
    health: 720,
    healthReg: 2.6,
    mana: 387,
    manaReg: 1.3,
    armor: 1.56,
    attackSpeed: 0.68,
    damage: "38‒45",
    moveSpeed: 285,
    attackRange: "range",
    roles: [
    "Support",
    "Disabler",
    "Nuker"
    ]
    },
    {
    id: 115,
    name: "Witch Doctor",
    url: "https://dota2.gamepedia.com/Witch_Doctor",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/3/33/Witch_Doctor_icon.png?version=73b2ab9afd2990f49faf54f4e8bd66aa",
    primaryAttribute: "Intelligence",
    health: 560,
    healthReg: 1.8,
    mana: 339,
    manaReg: 1.1,
    armor: 1.08,
    attackSpeed: 0.66,
    damage: "51‒61",
    moveSpeed: 300,
    attackRange: "range",
    roles: [
    "Support",
    "Nuker",
    "Disabler"
    ]
    },
    {
    id: 116,
    name: "Zeus",
    url: "https://dota2.gamepedia.com/Zeus",
    imgUrl: "https://gamepedia.cursecdn.com/dota2_gamepedia/3/3f/Zeus_icon.png?version=f80d75c5a638f7d875e49dc179b5143b",
    primaryAttribute: "Intelligence",
    health: 620,
    healthReg: 2.1,
    mana: 327,
    manaReg: 1.05,
    armor: 1.76,
    attackSpeed: 0.65,
    damage: "54‒62",
    moveSpeed: 295,
    attackRange: "range",
    roles: [
    "Nuker"
    ]
    }
    ]